baseURL = "https://example.com/"
title = "Cuau Cortés"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
disableLanguages = ["es", "it"]
disableKinds = ["section", "taxonomy", "term", "RSS", "sitemap"]

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    [languages.en.params]
      home = "Home"
      email = "me@cuaucortes.com"
      writing = "Writing"
  [languages.es]
    languageName = "Español"
    weight = 2
    contentDir = "content/es"
    [languages.es.params]
      home = "Inicio"
      email = "yo@cuaucortes.com"
      writing = "Escritos"
  [languages.it]
    languageName = "Italiano"
    weight = 3
    contentDir = "content/it"
    [languages.it.params]
      home = "Inizio"
      email = "io@cuaucortes.com"
      writing = "Scritti"
